### ISSUE TITLE
factor_to_maxclique list sometimes missing factor---->maxclique mapping

### ISSUE THREAD

**Issue by TeeRev** [jluttine/junction-tree#10] opened 2019-07-16 16:48 UTC
*Sometimes* when running ```prop_values = tree.propagate(values)``` in my scripts, I get the following error:

>   File "/home/teerev/Environments/py36/lib/python3.6/site-packages/junctiontree/junctiontree.py", line 57, in einsum
    xs[0],
IndexError: list index out of range

I have done the following checks:

1. The corresponding graphs do **not** have cycles in them. (checked by passing adjacency matrix to networkx.find_cycle)
2. Each graph has one only component. There are **no disconnected nodes**. (checked by passing adjacency matrix to scipy.sparse.csgraph.connected_components)

Here is a script that works:

```
from junctiontree import junctiontree as jt
import numpy as np

key_sizes = {'a': 10, 'b': 6, 'c': 3, 'd': 10, 'e': 27, 'f': 2, 'g': 3, 'h': 3, 'i': 3, 'j': 3, 'k': 5, 'l': 6}

factors = [
    ['f', 'g', 'a'],
    ['f', 'g', 'b'],
    ['c'],
    ['f', 'g', 'd'],
    ['g', 'e'],
    ['c', 'g', 'f'],
    ['c', 'g'],
    ['f', 'g', 'h'],
    ['f', 'l', 'i'],
    ['f', 'g', 'j'],
    ['f', 'g', 'k'],
    ['f', 'g', 'l']
]


values = [

np.random.random((key_sizes['f'], key_sizes['g'], key_sizes['a'])),
np.random.random((key_sizes['f'], key_sizes['g'], key_sizes['b'])),
np.random.random((key_sizes['c'])),
np.random.random((key_sizes['f'], key_sizes['g'], key_sizes['d'])),
np.random.random((key_sizes['g'], key_sizes['e'])),
np.random.random((key_sizes['c'], key_sizes['g'], key_sizes['f'])),
np.random.random((key_sizes['c'], key_sizes['g'])),
np.random.random((key_sizes['f'], key_sizes['g'], key_sizes['h'])),
np.random.random((key_sizes['f'], key_sizes['l'], key_sizes['i'])),
np.random.random((key_sizes['f'], key_sizes['g'], key_sizes['j'])),
np.random.random((key_sizes['f'], key_sizes['g'], key_sizes['k'])),
np.random.random((key_sizes['f'], key_sizes['g'], key_sizes['l'])),

]

tree = jt.create_junction_tree(factors, key_sizes)

prop_values = tree.propagate(values)
```

And here is one that does not work:

```
from junctiontree import junctiontree as jt
import numpy as np

key_sizes = {'a': 10, 'b': 6, 'c': 3, 'd': 10, 'e': 27, 'f': 2, 'g': 3, 'h': 3, 'i': 3, 'j': 3, 'k': 5, 'l': 6}

factors = [
    ['f', 'k', 'a'],
    ['f', 'g', 'b'],
    ['c'],
    ['f', 'k', 'd'],
    ['g', 'e'],
    ['c', 'g', 'f'],
    ['c', 'g'],
    ['f', 'h'],
    ['c', 'g', 'i'],
    ['l', 'j'],
    ['g', 'j', 'k'],
    ['g', 'l']
]

values = [

np.random.random((key_sizes['f'], key_sizes['k'], key_sizes['a'])),
np.random.random((key_sizes['f'], key_sizes['g'], key_sizes['b'])),
np.random.random((key_sizes['c'])),
np.random.random((key_sizes['f'], key_sizes['k'], key_sizes['d'])),
np.random.random((key_sizes['g'], key_sizes['e'])),
np.random.random((key_sizes['c'], key_sizes['g'], key_sizes['f'])),
np.random.random((key_sizes['c'], key_sizes['g'])),
np.random.random((key_sizes['f'], key_sizes['h'])),
np.random.random((key_sizes['c'], key_sizes['g'], key_sizes['i'])),
np.random.random((key_sizes['l'], key_sizes['j'])),
np.random.random((key_sizes['g'], key_sizes['j'], key_sizes['k'])),
np.random.random((key_sizes['g'], key_sizes['l']))

]

tree = jt.create_junction_tree(factors, key_sizes)
prop_values = tree.propagate(values)

```

If it may help, I also get the same 

> "xs[0], > IndexError: list index out of range"

 error when the underlying graph has two or more components (i.e. network consists of more than one component)

Please help!! Thank you.

**Comment by TeeRev** [comment] 2019-07-21 10:18
The cause appears to be somewhere in the function `beliefpropagation.find_triangulation()`.

For my two scripts above, find_triangulation() returns (in the working case)
```
factor_to_maxclique =   [7, 4, 0, 8, 9, 0, 0, 1, 5, 2, 3, 6]
maxcliques =  [['c', 'f', 'g'], ['f', 'g', 'h'], ['f', 'g', 'j'], ['f', 'g', 'k'], ['b', 'f', 'g'], ['f', 'i', 'l'], ['f', 'g', 'l'], ['a', 'f', 'g'], ['d', 'f', 'g'], ['e', 'g']]
```
and (in the buggy case):
```
factor_to_maxclique =  [8, 3, 2, 9, 6, 2, 2, 0, 1, 4, 5, 4]
maxcliques = [['f', 'h'], ['c', 'g', 'i'], ['c', 'f', 'g'], ['b', 'f', 'g'], ['g', 'j', 'l'], ['g', 'j', 'k'], ['e', 'g'], ['f', 'g', 'k'], ['a', 'f', 'k'], ['d', 'f', 'k']]
```

`set(factor_to_maxclique)` in the two cases gives
```
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
{0, 1, 2, 3, 4, 5, 6, 8, 9}
```


So the factor ---> maxclique mapping seems to be missing for the 7th maxclique in this example.

In the buggy case, the code segment (in junctiontree.py, CliqueGraph().evaluate()  (lines 207 - 213)

```     maxclique_to_factors = [
            [
                i for (i, y) in enumerate(self.factor_to_maxclique)
                if y == maxclique
            ]
            for maxclique in range(len(self.maxcliques))
        ]
```

results in an empty sublist since there is no "7" for y==maxclique to find, leading to the error in the title of this post.


Do you think this might be an easy fix? I'm happy to try to fix it myself, but it's so much faster with the original authors' oversight. Thank you.

**Comment by dar326** [comment] 2019-07-21 22:47
@TeeRev I'll take a look at this during the upcoming week.

**Comment by dar326** [comment] 2019-07-29 20:53
@TeeRev You should be all set here. The issue is that maxcliques were being created even in the case where there were no factors mapped to the maxclique which caused the error that you are seeing. The buggy case is now working properly. Closing this issue but please reopen if you are still experiencing issues.

**Closed by dar326** 2019-07-29 20:53 UTC
